[project]
authors = ["Paul Zimmerman"]
channels = ["conda-forge"]
description = "Package for automated reaction discovery developed in C++"
name = "ZStruct"
platforms = ["linux-64"]
version = "0.1.0"

# names of all dependencies as they appear on conda-forge
[dependencies]
dpcpp_linux-64 = ">=2021,<2023"
dpcpp-cpp-rt = ">=2021,<2023"
blas = ">=2,<3"
mkl-devel = ">=2021,<2022"
mkl-include = ">=2021,<2022"

[tasks.build]
# execute the Makefile
cmd = ["make", "-j4"]
inputs = ["*"]
outputs = ["zstruct.exe"]

[tasks.start]
# test the built executable on the input files in the tutorial directory
cwd = "tutorial"
cmd = "mkdir -p scratch; ../zstruct.exe; echo DONE"
depends-on = ["build"]

[tasks.clean]
cmd = ["make", "clean"]

[system-requirements]
linux = "3.10"
libc.version = "2.17"
