[project]
authors = ["Paul Zimmerman"]
channels = ["conda-forge", "https://software.repos.intel.com/python/conda/"]
description = "Package for automated reaction discovery developed in C++"
name = "ZStruct"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
# gxx = ">=14.1.0,<15"
# mkl-devel = ">=2024.2.1,<2025"
# mkl-include = ">=2024.2.1,<2025"
mkl-devel = ">=2021,<2022"
mkl-include = ">=2021,<2022"
blas = ">=2,<3"
# dpcpp-cpp-rt = ">=2024.1.0,<2025"
# dpcpp_linux-64 = ">=2024.1.0,<2025"
dpcpp-cpp-rt = ">=2021,<2023"
dpcpp_linux-64 = ">=2021,<2023"
# mkl = ">=2021,<2022"

[system-requirements]
linux = "3.10"
libc.version = "2.17"

[tasks.start]
# Start the built executable
cmd = "mkdir -p scratch; ./zstruct.exe; echo DONE"
depends-on = ["build"]

[tasks.build]
cmd = ["make", "-j4"]
# depends-on = ["clean"]
clean-env = true
inputs = ["*"]
outputs = ["zstruct.exe"]


# [tasks.build.env]
# LD_LIBRARY_PATH = ""

[tasks.clean]
cmd = ["make", "clean"]
